project_id = "clwghkbtkofacsjeyrtk"

[functions.blog-og-meta]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = true

[functions.create-paypal-order]
verify_jwt = true

[functions.verify-paypal-payment]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.generate-podcast-audio]
verify_jwt = true

[functions.generate-newsletter]
verify_jwt = true

[functions.send-newsletter]
verify_jwt = true
