import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Mail, ArrowLeft, CheckCircle, XCircle, Loader2, RefreshCw } from "lucide-react";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import { useToast } from "@/hooks/use-toast";
import authLogo from "@/assets/metsxmfanzone-logo-auth.png";

export default function ConfirmAccount() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const email = searchParams.get("email");
  const token = searchParams.get("token");
  const { toast } = useToast();

  const [verificationState, setVerificationState] = useState<"pending" | "verifying" | "success" | "error" | "waiting">("waiting");
  const [errorMessage, setErrorMessage] = useState("");
  const [resendLoading, setResendLoading] = useState(false);
  const [resendCooldown, setResendCooldown] = useState(0);

  // Cooldown timer
  useEffect(() => {
    if (resendCooldown > 0) {
      const timer = setTimeout(() => setResendCooldown(resendCooldown - 1), 1000);
      return () => clearTimeout(timer);
    }
  }, [resendCooldown]);

  // Verify token if present
  useEffect(() => {
    if (token && email) {
      verifyEmail();
    }
  }, [token, email]);

  const verifyEmail = async () => {
    if (!token || !email) return;

    setVerificationState("verifying");
    
    try {
      const normalizedEmail = email.toLowerCase().trim();
      
      const { data, error } = await supabase.functions.invoke('verify-email-confirmation', {
        body: { token, email: normalizedEmail },
      });

      // Handle edge function errors
      if (error) {
        console.error("Verification edge function error:", error);
        setVerificationState("error");
        setErrorMessage("Could not verify email. Please try again or request a new link.");
        return;
      }

      // Handle response errors
      if (data?.error) {
        console.error("Verification response error:", data.error);
        setVerificationState("error");
        setErrorMessage(data.error);
        return;
      }

      // Handle already verified case
      if (data?.alreadyVerified) {
        setVerificationState("success");
        toast({
          title: "Already Confirmed",
          description: "Your email was already confirmed. You can log in.",
        });
        return;
      }

      // Success
      setVerificationState("success");
      toast({
        title: "Email confirmed!",
        description: "Your account is now active. You can log in.",
      });
    } catch (err: any) {
      console.error("Verification exception:", err);
      setVerificationState("error");
      setErrorMessage("An error occurred during verification. Please try again.");
    }
  };

  const handleResendConfirmation = async () => {
    if (!email || resendCooldown > 0) return;

    setResendLoading(true);
    const normalizedEmail = email.toLowerCase().trim();
    
    try {
      // Look up user by email in profiles table (more reliable than tokens)
      const { data: profile, error: profileError } = await supabase
        .from("profiles")
        .select("id")
        .ilike("email", normalizedEmail)
        .maybeSingle();

      let userId = profile?.id;

      // If not found in profiles, try looking in tokens
      if (!userId) {
        const { data: existingToken } = await supabase
          .from("email_confirmation_tokens")
          .select("user_id")
          .ilike("email", normalizedEmail)
          .order("created_at", { ascending: false })
          .limit(1)
          .maybeSingle();

        userId = existingToken?.user_id;
      }

      if (!userId) {
        toast({
          title: "Account not found",
          description: "No account found for this email. Please sign up first.",
          variant: "destructive",
        });
        setResendLoading(false);
        return;
      }

      // Send confirmation email via edge function - it handles token creation
      const { data, error } = await supabase.functions.invoke('send-email-confirmation', {
        body: {
          email: normalizedEmail,
          name: "Mets Fan",
          userId: userId,
          // Token will be generated by the edge function
        },
      });

      if (error) {
        console.error("Resend edge function error:", error);
        throw new Error("Failed to send confirmation email");
      }

      if (data?.error) {
        throw new Error(data.error);
      }

      toast({
        title: "Confirmation email sent",
        description: "Please check your inbox (and spam folder) for the new confirmation link.",
      });
      setResendCooldown(60);
    } catch (err: any) {
      console.error("Resend confirmation error:", err);
      toast({
        title: "Failed to resend",
        description: err.message || "Unable to send confirmation email. Please try again later.",
        variant: "destructive",
      });
    } finally {
      setResendLoading(false);
    }
  };

  // Check if there's a pending plan selection
  const hasPendingPlan = localStorage.getItem("pending_signup_plan");
  
  const handleContinueAfterConfirmation = () => {
    if (hasPendingPlan) {
      navigate("/pricing?required=true");
    } else {
      navigate("/auth?mode=login");
    }
  };

  // Show success state
  if (verificationState === "success") {
    return (
      <div className="min-h-screen flex flex-col bg-gradient-to-b from-background to-background/95">
        <Navigation />
        <main className="flex-1 container mx-auto px-4 py-20 flex items-center justify-center">
          <Card className="w-full max-w-md border-green-500/50">
            <CardHeader className="text-center">
              <div className="mx-auto w-16 h-16 rounded-full bg-green-500/10 flex items-center justify-center mb-4">
                <CheckCircle className="w-8 h-8 text-green-500" />
              </div>
              <CardTitle className="text-2xl text-green-500">Email Confirmed!</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6 text-center">
              <p className="text-muted-foreground">
                {hasPendingPlan 
                  ? "Your account is now active. Please select your subscription plan to continue."
                  : "Your account has been successfully verified. You can now log in and start enjoying MetsXMFanZone!"
                }
              </p>
              <Button
                onClick={handleContinueAfterConfirmation}
                className="w-full bg-[#FF5910] hover:bg-[#FF5910]/90"
              >
                {hasPendingPlan ? "Select Your Plan" : "Continue to Login"}
              </Button>
            </CardContent>
          </Card>
        </main>
        <Footer />
      </div>
    );
  }

  // Show error state
  if (verificationState === "error") {
    return (
      <div className="min-h-screen flex flex-col bg-gradient-to-b from-background to-background/95">
        <Navigation />
        <main className="flex-1 container mx-auto px-4 py-20 flex items-center justify-center">
          <Card className="w-full max-w-md border-destructive/50">
            <CardHeader className="text-center">
              <div className="mx-auto w-16 h-16 rounded-full bg-destructive/10 flex items-center justify-center mb-4">
                <XCircle className="w-8 h-8 text-destructive" />
              </div>
              <CardTitle className="text-2xl text-destructive">Verification Failed</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6 text-center">
              <p className="text-muted-foreground">
                {errorMessage || "The confirmation link is invalid or has expired."}
              </p>
              <div className="space-y-3">
                <Button
                  variant="outline"
                  onClick={handleResendConfirmation}
                  disabled={resendLoading || resendCooldown > 0}
                  className="w-full"
                >
                  {resendLoading ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <RefreshCw className="mr-2 h-4 w-4" />
                  )}
                  {resendCooldown > 0 ? `Resend in ${resendCooldown}s` : "Resend Confirmation Email"}
                </Button>
                <Button
                  variant="ghost"
                  onClick={() => navigate("/auth?mode=login")}
                  className="w-full"
                >
                  <ArrowLeft className="mr-2 h-4 w-4" />
                  Back to Login
                </Button>
              </div>
            </CardContent>
          </Card>
        </main>
        <Footer />
      </div>
    );
  }

  // Show verifying state
  if (verificationState === "verifying") {
    return (
      <div className="min-h-screen flex flex-col bg-gradient-to-b from-background to-background/95">
        <Navigation />
        <main className="flex-1 container mx-auto px-4 py-20 flex items-center justify-center">
          <Card className="w-full max-w-md">
            <CardHeader className="text-center">
              <div className="mx-auto w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                <Loader2 className="w-8 h-8 text-primary animate-spin" />
              </div>
              <CardTitle className="text-2xl">Verifying Email...</CardTitle>
            </CardHeader>
            <CardContent className="text-center">
              <p className="text-muted-foreground">
                Please wait while we confirm your email address.
              </p>
            </CardContent>
          </Card>
        </main>
        <Footer />
      </div>
    );
  }

  // Default: waiting for confirmation (user just signed up)
  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-b from-background to-background/95">
      <Navigation />
      <main className="flex-1 container mx-auto px-4 py-20 flex items-center justify-center">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <div className="mx-auto mb-4">
              <img src={authLogo} alt="MetsXMFanZone" className="w-20 h-20 mx-auto" />
            </div>
            <CardTitle className="text-2xl">Check Your Email</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6 text-center">
            <div className="mx-auto w-16 h-16 rounded-full bg-[#FF5910]/10 flex items-center justify-center">
              <Mail className="w-8 h-8 text-[#FF5910]" />
            </div>
            
            <p className="text-muted-foreground">
              We've sent a confirmation link to:
            </p>
            {email && (
              <p className="font-semibold text-lg text-[#FF5910]">{email}</p>
            )}
            <p className="text-muted-foreground text-sm">
              Click the link in the email to activate your account. The link expires in 24 hours.
            </p>
            
            <div className="bg-muted/50 rounded-lg p-4 text-left">
              <p className="text-sm font-medium mb-2">Didn't receive the email?</p>
              <ul className="text-xs text-muted-foreground space-y-1">
                <li>• Check your spam or junk folder</li>
                <li>• Make sure you entered the correct email</li>
                <li>• Wait a few minutes and try again</li>
              </ul>
            </div>

            <div className="pt-4 space-y-3">
              <Button
                variant="outline"
                onClick={handleResendConfirmation}
                disabled={resendLoading || resendCooldown > 0}
                className="w-full"
              >
                {resendLoading ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <RefreshCw className="mr-2 h-4 w-4" />
                )}
                {resendCooldown > 0 ? `Resend in ${resendCooldown}s` : "Resend Confirmation Email"}
              </Button>
              <Button
                variant="ghost"
                onClick={() => navigate("/auth?mode=login")}
                className="w-full"
              >
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to Login
              </Button>
            </div>
          </CardContent>
        </Card>
      </main>
      <Footer />
    </div>
  );
}